### ISSUE TITLE
console.tag() nesting tags in different Modules

### ISSUE THREAD

**Issue by joaobrunoah** [bluejamesbond/Scribe.js#36]
Hi guys,

I'm using the tag function as follows:

    var scribe = require('scribe-js')();
    var console = process.console;
    var console = console.tag("MainModule").file();
    console.log("Hi mom!");

In another module i'm using:

    var console = process.console;
    var console = console.tag("SecondaryModule").file();
    console.log("Hi dad!");

However, when my second message appears, it appears as:

    [MainModule] [SecondaryModule] Hi dad!

Is there something I'm doing wrong? Can I modify the tag function to return a clone of the console, instead of the console itself?

**Comment by guillaumewuip** [comment]
Why don't you have done something like this ? 

```js
//main.js
require('scribe-js');
var console = process.console;

console.tag("MainModule").file().log("Hi !');
```
```js
//module.js
var console = process.console;
console.tag("Module").file().log("Hi dad !");
```

Actually, each time your using `tag`, 'file`, etc. methods, this return an instance of the console with properties where the args you passed to `tag("MainModule")`, by example, are stored. This properties are reset only after a logger call (ie. `.log("something")`, `debug`, etc.)

**Comment by guillaumewuip** [comment]
If you want to use default tags or default file logs for each logger call, you can : https://github.com/bluejamesbond/Scribe.js/wiki/4-%C2%B7-API-%3A-Console2#console2opt

**Comment by joaobrunoah** [comment]
Yes, I know. However, in my project I put a tag related to the module in which this log event occured. Therefore, for each module, I'd like to have a special tag on it. Since I have a lot of logs, I wouldn't like to change the whole code, inserting .tag() on each log event. What I did was clone the Console2 object on each module, and then update my cloned console with the desired tag for that module.

I thought that It'd be good to have this feature on console2 object instead of implementing this on every module. I know that there is a memory consumption issue there, but perhaps use as default your implementation and, if a certain flag or configuration is present, returns a clone of the console object when I request the process.console object.

**Comment by guillaumewuip** [comment]
Ok so I see.

Maybe you should try to not create the default console, but one console for each module and use defaut tags. 

```js
//main.js
var scribe = require('../scribe')({
    createDefaultConsole : false //Scribe won't attach a fresh console2 to process.console
});

var console = scribe.console({
    console : {                                      //Default options for all myConfigConsole loggers
        colors     : 'white',
        alwaysLocation : true,
        defaultTags : ["MainModule"]
    },
    createBasic : true                             //Create basic loggers
});

console.log("Hi mom!");  // [MainModule] [main.js:1]             Hi mom!

```

```js
//module.js
var scribe = require('../scribe')({
    createDefaultConsole : false 
});

var console = scribe.console({
    console : {                             
        colors     : 'white',
        alwaysLocation : true,
        defaultTags : ["SecondModule"]
    },
    createBasic : true 
});

console.log("Hi dad!");  // [SecondModule] [mdule.js:1]             Hi dad!
```

See also this example : https://github.com/bluejamesbond/Scribe.js/blob/master/examples/run_with_config.js

**Comment by joaobrunoah** [comment]
Ok @guillaumewuip 
Thanks a lot man! I'll use it as you suggested.

**Comment by joaobrunoah** [comment]
Just one thing that I forgot to mention. Thanks a lot for refactoring this module. The 1.x one was good, but this new version is much better :)

**Comment by joaobrunoah** [comment]
Hi Guillaume.

The suggested solution caused a conflict regarding the folder in which each console will write. The thrown error is

    throw new Error('Folder ' + this.rootPath + ' already in use')
    Error: Folder logs already in use

Is there a way to solve it? does it exist to avoid a conflict writing in the same file?

**Comment by guillaumewuip** [comment]
Oh, I forgot to mention the LogWriter config. As there is one log folder for one console, you should give another folder for the second one.

```js
//module.js
var scribe = require('../scribe')({
    createDefaultConsole : false 
});

var console = scribe.console({
    console : {                             
        colors     : 'white',
        alwaysLocation : true,
        defaultTags : ["SecondModule"]
    },
    createBasic : true,
    logWriter : {
        rootPath : 'logsConsoleOne' //all logs in ./logsConsoleOne
    }
});

console.log("Hi dad!");  // [SecondModule] [mdule.js:1]             Hi dad!

```

Normally the webPanel will show you the 2 folder in the sidebar.

**Comment by joaobrunoah** [comment]
@guillaumewuip , thanks again for your response. I really don't want to be picky, but I didn't want to have multiple log files to the same date for the same type of log ("log", "info", etc...). One thing I thought was to develop a Semaphore to write in the log files. Do you think it will work? Therefore, it would control file access, and enable two or more consoles to write in the same folder, keeping the logs together. If you think it's fine but don't have time, I could implement that.

**Comment by bluejamesbond** [comment]
@joaobrunoah The reason @guillaumewuip and I decided to do that was because people use different types of logs for different reasons. For instance, in my apps I have a stream for large data just for the sake of keeping track, while other streams are used for short quick logging usually used for debugging. With the large variances in file size depending on the type of log, we noticed that combining the outputs of the two logs would be hinder the a developer who wants to quickly access debug data. Since loading we are loading "one" file we are loading all the content all the data at once. So, we split them up in order to be able to select any log you want to view. If you want just the small debug log, just load that up meanwhile if you want to load the large data log, you can do that as well. And in event you want to view the two together, the Scribe web-interface provides that feature as well. @guillaumewuip 's LogWriter module is in essence a "semaphore". I would highly recommend modifying his module and enabling single file output as an option that people can enable/disable as they wish.

**Comment by guillaumewuip** [comment]
Yes in fact, it's simply a condition that prevent the multiple console / one log folder case. 
I've push an pull request #37 without it. It seems to work.

By the way, I'm not totally that the LogWriter is a good semaphore. I once found corrupted `history.json` file without understanding why.

**Comment by bluejamesbond** [comment]
@joaobrunoah @guillaumewuip I apologize. Tt seems as if I misunderstood your question. I am glad a solution was found.

**Comment by viksat7** [comment]
@guillaumewuip  thanks for the solution
