### ISSUE TITLE
Web panel on IE

### ISSUE THREAD

**Issue by matteocontrini** [bluejamesbond/Scribe.js#41]
The web panel interface is not working on Internet Explorer 11.
When you tap the "refresh" button, nothing happens.

**Comment by bluejamesbond** [comment]
@matteocontrini Can you please provide a screenshot of the full explorer page and include your source code where you use Scribe.js

**Comment by matteocontrini** [comment]
It is working correctly now. No problem.
But not on Internet Explorer mobile (on Windows Phone 8.1). When I tap the button, it is highlighted but the view is not refreshed. Difficult to debug though.

**Comment by bluejamesbond** [comment]
Mobile unfortunately will be tough to support at the moment esp. with the type of data being presented. Perhaps a feature for the future. I am closing now. Please reopen as needed. Be sure to checkout the latest version running on the `dev` branch.
