### ISSUE TITLE
node-webkit with scribe.js, cant find the 'logs' folder

### ISSUE THREAD

**Issue by estvmachine** [bluejamesbond/Scribe.js#48]
Well i just make a package with node-webkit, and well the scribe.js still working, however i cant find the 'logs' folder, any idea where is it?. I search inside the package, in the desktop, in the root folder of the package, in the temps files, i search with windows explorer the files like the image and nothing,

![image](https://cloud.githubusercontent.com/assets/2062668/7869144/d193d706-054e-11e5-9c01-90ffd11e9c87.png)

I thinks is creating files because when i close the app, i can reach the same logs, and on purpose i generated error for charging the 'logs error'. Well maybe you can help me.

**Comment by guillaumewuip** [comment]
Hi @estvmachine, sorry for having forgot to respond here. I was busy and I think @bluejamesbond is too.
You've just closed this issue. Is it to say you've find a solution ?

**Comment by estvmachine** [comment]
Yeah i think use temp, its more a question about funcionality of node and windows than this plugin.

**Comment by guillaumewuip** [comment]
Thanks for your feedback @estvmachine, I didn't know this node-webkit trick.
