### ISSUE TITLE
How i add new category of Log

### ISSUE THREAD

**Issue by estvmachine** [bluejamesbond/Scribe.js#49]
I see the plugin create the category for log, error, info, etc.

And then when i use it, i can use a command like:

```javascript
   console.tag('some info').log('Put something here')
```

How i create a new category like for example 'querie'
```javascript
  console.tag('a querie').querie('SELECT * FROM ....')
```
I can be done something like that with Scribe?

**Comment by guillaumewuip** [comment]
Hi @estvmachine, you can add your logger this way :

```js
console.addLogger('querie');
console.tag("Argggg").querie("Need help !");
}());
```
See the wiki https://github.com/bluejamesbond/Scribe.js/wiki/4-%C2%B7-API-%3A-Console2#console2addloggername-colors-opt for more infos :)

**Comment by estvmachine** [comment]
Thanks ! :D
