### ISSUE TITLE
/logs does not load any of the log json data.

### ISSUE THREAD

**Issue by NukaPunk** [bluejamesbond/Scribe.js#50]
I wanted to first say that you've done some great work with this logging system! I've got it configured in my test app, and I'm writing logs to files with barely any setup. However, I'm having an issue that I was hoping you could help with.

I've got a config file set up like this:

``` javascript
(function (loggingConfig) {

    var scribe = require('scribe-js')();
    var passport = require('passport');


    //loggingConfig.LogWriter = new scribe.LogWriter('logger');

    loggingConfig.console = process.console;

    loggingConfig.init = function (app) {

        console.log('Configuring logging.');

        //Log each request
        app.use(scribe.express.logger());

        console.log('Adding logging panel');

        app.use('/logs', scribe.webPanel());

    };
})(module.exports);
```

I can see files in my logs folder, and can read the JSON inside of them. However, when I browse to the /logs page this is all I get:

![image](https://cloud.githubusercontent.com/assets/6144177/8293809/a0155020-18fd-11e5-9be0-8df9d0395f43.png)

I don't see any bugs in the console (node or browser) so I'm not sure what might be happening. Let me know what else I can do to help troubleshoot this issue!

Thanks

**Comment by guillaumewuip** [comment]
Hi @NukaPunk, maybe the `console` object is not pointing to the `process.console`.
Can you try something like below ?

```js
loggingConfig.console = process.console;
var console = logging.console;

console.log('This should be a Console2 message');
```

**Comment by NukaPunk** [comment]
Thanks for the quick reply!

Yup that's exactly what I'm doing. Above you can see the line ```loggingConfig.console = process.console;``` and then when I include the module (let's say logging.js) I do the following:

``` javascript
var log = require('./logging');
log.console.error('This should be a Console2 message');
```

It logs to the console just fine, and the files just fine too. But the browser doesn't display them at all. 

Are perhaps any permissions I have to set on the folder? I know scribe makes the folders itself so I didn't assume so.

Thanks again!

**Comment by guillaumewuip** [comment]
Ok, I first thought it was the `console.log` you used in your module that doesn't work.
Using your browser developers tools, do you see any failed request ?

**Comment by NukaPunk** [comment]
Nope not a thing. Do you want me to post the markup of the page or anything to help? I could try throwing some break points in the Angular files and see what's going on.

**Comment by bluejamesbond** [comment]
Hey Joseph,
Can you post a dump/screenshot of all the network requests by the browser?
Review the responses as well. Just to make sure the data is reaching the
browser.

**Comment by NukaPunk** [comment]
Looks like it's working now! I was in-fact a local permissions issue. Thanks guys.

Quick question: How do you view the error logs specifically? When I load the panel I see "Logs" and then all of the dates, and then just all of the request logs. But not any of the errors I logged using the method above. Ideas?

**Comment by bluejamesbond** [comment]
Also look at the logs folder in your root directory of your node app. Let
us know what you see. Thanks

**Comment by NukaPunk** [comment]
Yup all of the log files are there, of each level (error, info, etc) for each day.

**Comment by NukaPunk** [comment]
Got it figured out guys. Thanks for the help! What an awesome project!

**Comment by NukaPunk** [comment]
I just wanted to note that I'm going to suggest this to all of my students :+1:

**Comment by bluejamesbond** [comment]
I'm glad it all worked out and thank you. We appreciate that.
