### ISSUE TITLE
Choose folder where logs saving

### ISSUE THREAD

**Issue by estvmachine** [bluejamesbond/Scribe.js#52]
Hi, how can i choose where the 'logs' are saving. I want to save them in AppData, but its seems automacally save in the root of my folder project.

**Comment by estvmachine** [comment]
I answer myself, when create the object log then you have to pass the object options with 'rootPath' with the direction that you want:

´´´javascript
scribe = require('scribe-js')({rootPath: process.env.HOME+ '/AppData/NAME_YOUR_SOFTWARE/logs' });

´´´

**Comment by guillaumewuip** [comment]
You're right, for more config options have a look in the wiki : https://github.com/bluejamesbond/Scribe.js/wiki/4-%C2%B7-API-%3A-Scribe :)

**Comment by estvmachine** [comment]
Oh you are right, the wiki says that, but its only one line xd. Anyways thanks for your wonderful job.
