### ISSUE TITLE
writing to a file?

### ISSUE THREAD

**Issue by dcsan** [bluejamesbond/Scribe.js#58]
looking for some basic info how to write logs to a file?

i see `some().long().file()` toy code but nothing with a basic explanation in the docs.

**Comment by guillaumewuip** [comment]
Actually, the `console.file().log()` will simply append the filename and the line number of the `console.log()` command into the log. See the [doc](https://github.com/bluejamesbond/Scribe.js/wiki/4-%C2%B7-API-%3A-Console2#console2file-console2f).

What you need to save logs to file is activate the logWriter. Please, check this example : https://github.com/bluejamesbond/Scribe.js/blob/master/examples/logWriter_config.js

**Comment by dcsan** [comment]
thanks, found a comment on another ticket eventually.
