### ISSUE TITLE
Saving to a database?

### ISSUE THREAD

**Issue by kokujin** [bluejamesbond/Scribe.js#63]
Are there any examples that show how to save Scribe logs to a database? Thanks

**Comment by AshotN** [comment]
Is there any reason you would want to?

**Comment by kokujin** [comment]
Scalability, I could query logs from a database from anywhere then

**Comment by bluejamesbond** [comment]
For such scalability, I suggest using more powerful tools like Splunk. Closing for now since this library was meant to serve as a lightweight solution for smaller applications i.e. internal tools.
