### ISSUE TITLE
Could not find es6 branch to clone

### ISSUE THREAD

**Issue by marcosPerezRubio** [bluejamesbond/Scribe.js#74]
In description there is written the following command to try the new version of the logger:

git clone https://github.com/bluejamesbond/Scribe.js --branch  es6 --single-branch && cd Scribe.js && npm install && npm run babel-node ./examples/simple-server.js

But i get an error saying that there is no branch named es6, so i suppose that is the dev branch instead.

**Comment by bluejamesbond** [comment]
Do you mean this branch? https://github.com/bluejamesbond/Scribe.js/tree/dev

**Comment by marcosPerezRubio** [comment]
Yup, my points is that the command should be:

git clone https://github.com/bluejamesbond/Scribe.js --branch **dev **--single-branch && cd Scribe.js && npm install && npm run babel-node ./examples/simple-server.js

**Comment by bluejamesbond** [comment]
I updated it as such. Thank you. I'm closing this issue. Please reopen as necessary
