### ISSUE TITLE
Wrong npm package on Scribe 3.0 page

### ISSUE THREAD

**Issue by charliebrink** [bluejamesbond/Scribe.js#84]
I think the link on the Scribe 3.0 page (https://github.com/bluejamesbond/Scribe.js/tree/dev) should be 

`npm install scribe-js@3.0.0-alpha.10` 

instead of 

`npm install scribe@3.0.0-alpha.10`.

**Comment by bluejamesbond** [comment]
Thanks for bringing it up. I have fixed it.
